<script>
    
    function dump(obj) {
var out = '';
for (var i in obj) {
out += i + ": " + obj[i] + "\n";
}

alert(out);
}
    
function showHint(id){
    
                    var result = new Array();
                    var option = $('input:radio[name=option]:checked').val();
                    
                    $.ajax({
                        url: 'admin/bookings/booking/search/',                      
                        type: "POST",
                        data: {
                            q : id,
                            option : option
                        },                       
                        dataType: 'json',   
                        async: false,
                        success: function(data)  {
                            result = data;
                       
                              $("#txtHint").html(result);
                        }
                    });
    
                   
                
       }
       
       function insert(bookingid,venueid){
    
                    var result = new Array();
                    
                    var user = document.getElementById('txtHint').innerHTML;
                    var option = $('input:radio[name=option]:checked').val();

                    $.ajax({
                        url: 'admin/bookings/booking/insert/',                      
                        type: "POST",
                             data: {   
                             user : user, 
                             bookingid : bookingid,
                             venueid : venueid,
                             option : option
                         },                     
                        dataType: 'json',   
                        async: false,
                        success: function()  {
                            
                            location.reload(true);
                            
             
                        }
                    });
    
                   
                
       }
            
</script>

<h1>Game list</h1>

<div id ="container">
        
    <div id ="left">&nbsp;</div>
    <div id ="center">
    <table id="slot_booking">

        <h3 align="center"><?php echo $this->escape($this->date);?></h3>
        <?php foreach ($this->names as $key => $r): ?>

            <tr>
                <td>Player <?php echo $this->escape($key+1); ?></td>
                <td> - </td>
                <td><?php echo $this->escape($r['name']); ?> </td>
                <td> (Player pre registered) </td> 
                 <?php if ($r['playerid'] == $this->temp_playerid): ?>
                <td><a href="<?php echo $this->url(array('bookingid' => $r['booking_gameid'], 'venueid' => $this->venueid),  'admin-bookings-cancelbooking', 'default', true); ?>">(Cancel)</a></td>
                  <?php endif; ?>
                             <?php if ($this->access == 'venue' && $this->auth == 'yes'): ?>
                <td><a href="<?php echo $this->url(array('bookingid' => $r['booking_gameid'], 'venueid' => $this->venueid, 'playerid' => $r['playerid']),  'admin-bookings-venuecancelbooking', 'default', true); ?>">(Cancel)</a></td>
                  <?php endif; ?>
            </tr>

        <?php endforeach; ?>   
        <?php for ($this->slot_place; $this->slot_place <= 16; $this->slot_place++): ?>  
            <tr>
                <td>Slot:   <?php echo $this->escape($this->slot_place); ?> </td>
                <td> - </td>
                <?php if ($this->access == 'player'): ?>
                <td><a href="<?php echo $this->url(array('bookingid' => $this->bookingid, 'venueid' => $this->venueid),  'admin-bookings-bookupdate', 'default', true); ?>">Book Slot</a></td>
                <?php endif; ?>
            </tr>
        <?php endfor; ?> 
                </table>
        <br>
            <table id="slot_booking">

                <?php if ($this->slot_place_other > 3 && $this->paid == 'No' && $this->access == 'venue' && $this->auth == 'yes'): ?>

                    <tr>

                        <td>
<?php if ($this->type == "veune"):?>
    
                                    <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
                                        <input type="hidden" name="cmd" value="_xclick">
                                        <input type="hidden" name="business" value="646MHWRA2NRKQ">
                                        <input type="hidden" name="lc" value="GB">
                                        <input type="hidden" name="item_name" value="Tripjackspaco Buy Venue Game">
                                        <input type="hidden" name="amount" value="30.00">
                                        <input type="hidden" name="currency_code" value="GBP">
                                        <input type="hidden" name="button_subtype" value="services">
                                        <input type="hidden" name="no_note" value="0">
                                        <input type="hidden" name="cn" value="Add special instructions to the seller:">
                                        <input type="hidden" name="no_shipping" value="1">
                                        <input type="hidden" name="rm" value="1">
                                        <input type="hidden" name="cancel_return" value="http://tripjackspaco.com/leagues/league/specialindex/<?php echo $this->escape($this->subleague[0]['subleagueid']); ?>">                             
                                        <input type="hidden" name="custom" value="<?php echo $this->escape($this->bookingid); ?>">
                                        <input type="hidden" name="return" value="http://tripjackspaco.com/admin/bookings/booking/buyupdate/<?php echo $this->escape($this->bookingid); ?>/<?php echo $this->escape($this->venueid); ?>">
                                        <input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynow_LG.gif:NonHosted">
                                        <input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online.">
                                        <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
                                    </form>

                            
<?php elseif($this->type == "skirmish"):?>

                            
                                            <form action="https://www.paypal.com/cgi-bin/webscr" method="post">
                                        <input type="hidden" name="cmd" value="_xclick">
                                        <input type="hidden" name="business" value="646MHWRA2NRKQ">
                                        <input type="hidden" name="lc" value="GB">
                                        <input type="hidden" name="item_name" value="Tripjackspaco Buy Skirmish Game">
                                        <input type="hidden" name="amount" value="10.00">
                                        <input type="hidden" name="currency_code" value="GBP">
                                        <input type="hidden" name="button_subtype" value="services">
                                        <input type="hidden" name="no_note" value="0">
                                        <input type="hidden" name="cn" value="Add special instructions to the seller:">
                                        <input type="hidden" name="no_shipping" value="1">
                                        <input type="hidden" name="rm" value="1"
                                        <input type="hidden" name="cancel_return" value="http://tripjackspaco.com/leagues/league/specialindex/<?php echo $this->escape($this->subleague[0]['subleagueid']); ?>">                             
                                        <input type="hidden" name="custom" value="<?php echo $this->bookingid; ?>">
                                        <input type="hidden" name="return" value="http://tripjackspaco.com/admin/bookings/booking/buyupdate/<?php echo $this->escape($this->bookingid); ?>/<?php echo $this->escape($this->venueid); ?>">
                                        <input type="hidden" name="bn" value="PP-BuyNowBF:btn_buynow_LG.gif:NonHosted">
                                        <input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online.">
                                        <img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
                                    </form>

<?php endif; ?>
                        </td>
                    </tr>

                <?php endif; ?>

                <?php if ($this->paid == "Yes" && $this->access == 'venue' && $this->auth == 'yes' && $this->slot_place_other > 3): ?>

                    <tr>

                        <td><a href="<?php echo $this->url(array('bookingid' => $this->bookingid, 'venueid' => $this->venueid), 'admin-games-index', 'default', true); ?>"><div id="click_box">Game Set up</div></a></td>

                    </tr>

                <?php endif; ?>
                    
                    <?php if ($this->access == 'venue' && $this->auth == 'yes'): ?>
                    
                    <tr><td></td></tr>
                                
                        <tr>
                            
                            <td>
                                <h3>Start typing a username in the input field below:</h3>
                       <table>
                                     <tr><td>Username: <input type="text" id="txt1" onkeyup="showHint(this.value)" /></td></tr>
                                        
                                    <tr><td>Search By: <input type="radio" name="option" id="option" checked="checked" value="memberno">Member Number
                                            <input type="radio" name="option" id="option" value="username">Username
                                        </td>
                                    </tr>
                        
                              <tr><td>  <p>Suggestions: <span onclick="insert(<?php echo $this->escape($this->bookingid); ?>,<?php echo $this->venueid; ?>)" style="cursor:pointer" id="txtHint"></span> (Click username to add player to game)</p> 
                            </td>    
                        </tr>
            </table>
                    <?php endif; ?>


                                <tr>
        <td><button onclick="history.go(-1)">Back</button></td>
    </tr>


            </table>
        
        <br>
           
        
</div>
    <div id ="right">&nbsp;</div>

</div>

  

  

