


<?php
$this->headLink()->appendStylesheet('/css/main.css');
$this->headScript()->appendFile('/js/form.js');
?>





<div id ="container">
        
    <div id ="left">----left col------
    
    
    
    <div id="images">
        

    <?php foreach ($this->images as $image): ?>
    <img src="/infouploads/<?php echo $this->escape($image); ?>" width="150" height="150" />    
    <?php endforeach; ?>
  </div>
    
    </div>
   
    <div id ="center">
        <h2> <?php echo $this->info['title']; ?></h2>
        
                <?php echo $this->info['info']; ?>


</div>

    <div id ="right">----right col------</div>

</div>

  
