<h2>Main body's</h2>
<?php if (count($this->records)): ?>
<div id="records">
  <form method="post" action="
      <?php echo $this->url(array(), 'admin-mains-delete'); ?>">
    <table>
      <tr>
        <td></td>    
        <td class="key">
          Main ID
        </td>
        <td class="key">
          Body:
        </td>
   
        <td></td>    
        <td></td>    
      </tr>
      <?php foreach ($this->records as $r):?>
      <tr>
        <td><input type="checkbox" name="ids[]" value="<?php echo $r['mainid']; ?>" style="width:2px" /></td>
        <td><?php echo $this->escape($r['mainid']); ?></td>
        <td><a href="<?php echo $this->url(array('id' => $r['mainid']), 'admin-mains-display'); ?>">Display</a></td>    
        <td><a href="<?php echo $this->url(array('id' => $r['mainid']), 'admin-mains-update'); ?>">Update</a></td>    
      </tr>  
      <?php endforeach; ?>
      <tr>
        <td colspan="9"><input type="submit" name="submit" style="width:150px" value="Delete Selected" /></td>
      </tr> 
            <tr>
        <td colspan="9"><a href="<?php echo $this->url(array(), 'admin-mains-create'); ?>">Add new main page</a></td>
      </tr> 
    <tr>
        <td colspan="9"><a href="<?php echo $this->url(array(), 'admin-mains-upload'); ?>">Upload Pics</a></td>
      </tr> 
       
    </table>
  </form>
</div>

<?php else: ?>
No records found
</br>
<a href="<?php echo $this->url(array(), 'admin-mains-create'); ?>">Add new main page</a>
<?php endif; ?>
