<h1>Venue List</h1>



<div id ="container">

    <div id ="left">&nbsp;</div>

    <div id ="center">




        <table id="records">

            <?php if (count($this->venue)): ?>

                <tr>
                    <th><h2>Select Venues</h2></th>

                </tr>



                <?php foreach ($this->venue as $r): ?>
                    <tr>

                        <?php if ($r['propic'] == ""): ?>
                            <td><img src="/venuepro/nopic.JPG" height="75px" width="75px"> </td>
                        <?php else: ?>
                            <td><img src="/venuepro/<?php echo $r['propic']; ?>" height="75px" width="75px"> </td>
                        <?php endif; ?>


                        <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                            <td><a href="<?php echo $this->url(array('venueid' => $r['venueid']), 'admin-bookings-gameindex', 'default', true); ?>"><?php echo $this->escape($r['name']); ?></a></td>
                        <?php else: ?>
                            <td><a href="<?php echo $this->url(array('venueid' => $r['venueid']), 'bookings-gamedisplay', 'default', true); ?>"><?php echo $this->escape($r['name']); ?></a></td>
                        <?php endif; ?>
                    </tr>

                <?php endforeach; ?>


            <?php else: ?>
                No Venues Added!
            <?php endif; ?>

            <tr>
                <td><button onclick="history.go(-1)">Back</button></td>
            </tr>

        </table>

    </div>
    <div id ="right">&nbsp;</div>

</div>




