
<div id ="container">

    <div id ="left">&nbsp;</div>
    <div id ="center">
        <h2>Login</h2>
        <div style="color:red; font-weight:bolder">
            <?php echo $this->escape($this->message); ?>
        </div>
        <?php echo $this->form; ?>
        <p style="font-size:14px;"><a href="<?php echo $this->url(array(), 'request'); ?>">Lost Password?</a></p>
    </div>
</div>
<div id ="right">&nbsp;</div>

</div>