<?php

/**
 * Tripjacks_Model_Attendance
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tripjacks_Model_Attendance extends Tripjacks_Model_BaseAttendance
{
    
    
    public function setUp() {
        $this->hasOne('Tripjacks_Model_Player', array(
            'local' => 'playerid',
            'foreign' => 'playerid'
                )
        );
        $this->hasOne('Tripjacks_Model_Venue', array(
            'local' => 'venueid',
            'foreign' => 'venueid'
                )
        );
    }
    
    
    
    

}