<style>
    p{
        color:white;
       text-align:justify;
    }
</style>

<div id ="container">

    <div id ="left">&nbsp;</div>

    <div id ="center">
        

<h1 align = "center">Privacy Policy</h1>
<br>


 <h3><br>Our Commitment To Privacy</h3>
      <p>Your privacy is important to us. To better protect your privacy we provide 
        this notice explaining our online information practices and the choices you 
        can make about the way your information is collected and used. To make this 
        notice easy to find, we make it available on our homepage and at every point 
        where personally identifiable information may be requested. </p><br><br>


      <h3>The Information We Collect: </h3>
      <p>This notice applies to all information collected or submitted on this website. 
        On some pages, you can order products, make requests, and register to receive 
        materials. The types of personal information collected at these pages are: 
      </p>
      <p>Name <br>
        Username <br>
        Email address <br>
        Address (venue Only)<br>   
        County (venue Only)<br>
        Date of Birth (player Only)<br>
        Game results (player Only)<br>
        Game info (player Only)<br>
        <br>
        On some pages, you can submit information about other people. For example, If a client creates a test on a students personal details.
	We will not supply this information to the Client. This will be an agreement between the student and client. </p>
 </p><br><br>


      <h3>The Information We DONT Collect:</h3>
      <p>Credit/Debit Card Information. (See <a href="<?php echo $this->url(array('page' => 'tandc'), 'static-content'); ?>">Terms and Conditions/Subscription Agreement)</a> </p><br><br>


      <h3>The Way We Use Information:</h3>
      <p>We use the information you provide about yourself, only to comunicate and to identify you.
	 We do not share this information with outside parties 
        except to the extent necessary to complete that order. </p>
   

      <p>We use return email addresses to answer the email we receive. Such addresses 
        are not used for any other purpose and are not shared with outside parties. 
      </p>
      <p>When you register with our website, this gives us confirmation that we can email you for necessary reasons.
	For example, update notification, password change, student/client test notification and  cancellations.
	Information you submit on our website will not be used for this purpose unless you fill out the registration 
        form. </p>


      <p>We use non-identifying and aggregate information to better design our website 
        and to share with advertisers. For example, we may tell an advertiser that 
        X number of individuals visited a certain area on our website, or that Y number 
        of men and Z number of women filled out our registration form, but we would 
        not disclose anything that could be used to identify those individuals. </p>
      <p>Finally, we never use or share the personally identifiable information provided 
        to us online in ways unrelated to the ones described above without also providing 
        you an opportunity to opt-out or otherwise prohibit such unrelated uses. </p><br><br>


      <h3>Our Commitment To Data Security</h3>
      <p>To prevent unauthorized access, maintain data accuracy, and ensure the correct 
        use of information, we have put in place appropriate physical, electronic, 
        and managerial procedures to safeguard and secure the information we collect 
        online. </p><br><br>


      <h3>How You Can Access Or Correct your Information</h3>
      <p>You can access all your personally identifiable information that we collect 
        online and maintain by <a href="<?php echo $this->url(array(), 'contact'); ?>">calling us or sending 
        us an email</a>.. We use this procedure to better safeguard your information. 
      </p>
      <p>You can correct factual errors in your personally identifiable information 
        by sending us a request that credibly shows error. </p>
      <p>To protect your privacy and security, we will also take reasonable steps 
        to verify your identity before granting access or making corrections. </p><br><br>

	<h3>Changes to this policy</h3>
	<p>This policy was last edited March 2011. We reserve the right to amend this privacy statement. You are advised to visit this website 
	section periodically in order to keep up to date with the changes in our privacy policy.</p><br><br>

      <h3>How To Contact Us</h3>
      <p>Should you have other questions or concerns about these privacy policies, 
        please <a href="<?php echo $this->url(array(), 'contact'); ?>">contact us</a> .<br>
        &nbsp; </p><br>


        
    </div>
    
    <div id ="right">&nbsp;</div>

</div>
                
       
     