<?php
$this->headLink()->appendStylesheet('/css/center.css');
?>





<div id ="container">

    <div id ="left">&nbsp;</div>

    <div id ="center">

        <h1 align ="center">Generate more revenue – regularly</h1>

<p align="justify" style="color:white;">You may have heard of In-Pub poker, it's been around for a while and has been used to generate footfall and revenue for pubs all over the UK. TripJacksPACo has taken this a step further than other pub-poker companies. Not only does the TripJacksPACO system minimise the administration you have, it also provides Twitter and Facebook feeds, enabling your poker players to talk to each other, arrange meets at your venue, and create  a 'poker community' with your pub at it's heart.</p>

<p align="justify" style="color:white;">Operating strictly within the law regarding public gambling, the TripJacksPACO system allows for increased excitement and interest for those players keen on 'more ambitious' stakes!</p>

<p align="justify" style="color:white;">Weekly venue league games, plus 'ad hoc' player demand games (Special Leagues) bring poker regularly and frequently to your pub, giving you multiple revenue streams.</p>

<p align="justify" style="color:white;">The system is Internet based, very simple to operate and requires no 'after-game' administration on your part – it is all automatic.</p>

<p align="justify" style="color:white;">Register your venue with TripJacksPACO and you will have generated all the games available for the current season, for your players to pre-register for. If there aren't enough players (usually a table of 8), you don't play the game and you are not charged for it:</p>

<h2 align="center" style="color:white;">'No Play – No Pay' – simple as that!</h2>

<p align="justify" style="color:white;">Registration is free, you only pay for games that actually take place, and even then, it's cheaper than any other pub-poker company.</p>

<p align="justify" style="color:white;">When you register, we will send you a welcome email, with detailed instructions as necessary, plus marketing materials to give your the best chance of boosting your revenues with poker In your pub.</p>

<h2 align="center" style="color:white;"><a href="/home">www.tripjackspaco.com</a></h2>

<h2 align="center" style="color:white;">Please be sure to put our <a href="mailto:info@tripjackspaco.com?Subject=VenueAdvert%20Enquiry">email</a> in your address book:
info@tripjackspaco.com</h2>

<h2 align="center" style="color:white;">Do you have, or would you like to acquire tables, chips, cards, etc?</h2>

<h2 align="center" style="color:white;">If you need these, please either <a href="mailto:info@tripjackspaco.com?Subject=VenueAdvert%20Enquiry">email</a>, or call: 07737170035</h2>



    </div>
    <div id ="right">&nbsp;</div>

</div>



