<h2>View Sub League</h2>
<h3>
  <?php echo $this->escape($this->league['name']); ?> - 
</h3>

<div id="container">
  <div id="record">  
    <table>
      <tr>
        <td class="key">Name:</td>
        <td class="value">
          <?php echo $this->escape($this->league['name']); ?>
        </td>
      </tr
      <tr>
        <td class="key">Description:</td>
        <td class="value">
          <?php echo $this->league['description']; ?>
        </td>
      </tr>
      <tr>
    </table>
  </div>  
</div>
